# Fetching the latest node image on alpine linux
FROM node:alpine AS development

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /react-app

# Installing dependencies
COPY ./package*.json /react-app

RUN npm install

# Copying all the files in our project
COPY . .

# Set Traefik labels
LABEL "traefik.enable"="true"
LABEL "traefik.http.routers.scriptertechnology.rule"="Host(`scriptertechnology.com`)"
LABEL "traefik.http.routers.scriptertechnology.tls"="true"
LABEL "traefik.http.routers.scriptertechnology.tls.certresolver"="lets-encrypt"
LABEL "traefik.http.services.scriptertechnology.loadbalancer.server.port"="1001"

# Starting our application
CMD ["npm","start"]